### ISSUE TITLE
FiftyOne.Pipeline.Web v4.4.16+ does not support .NET Framework anymore

### ISSUE THREAD

**Issue by nilayk** [51Degrees/pipeline-dotnet#27]
Trying to upgrade from `FiftyOne.Pipeline.Web` `v4.4.15` to a higher version `v4.4.16+`, but it seems that .NET Framework is not supported by more recent package versions anymore. I'm getting the following error while upgrading using Nuget:

> Could not install package 'FiftyOne.Pipeline.Web 4.4.20'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.7.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

All the other packages under `FiftyOne.Pipeline` project continue supporting .NET Framework 4.7+

Was this obsoletion of .NET Framework 4.7+ support intentional?

**Comment by kirstin51D** [comment]
Hi! Thanks for raising this. It's not intentional as we do plan to support .NET Framework 4.7+. However during investigations, we've discovered a bug in the release process. Until we can sort the issue, I recommend that you should use 4.4.15 and not 4.4.16. 

We'll keep you updated on the progress of the bug fix. 
Thanks!
Kirstin

**Comment by kirstin51D** [comment]
Hi @nilayk. At the end of last week we implemented a bug fix that should resolve the issue. If you are still experiencing issues, do let us know. We will be closing our internal support ticket unless we hear otherwise.
Kind regards
Kirstin
